%% Zachary Kaplan
 % Math 440
 % Computational Lab #4
 % 5/3/19
 
%%%
% An online version of this file can be found published to:
% https://www.overleaf.com/read/wwdtnstrvpqz
% 
% *NOTE*: To render this file locally, please prepend the following package
%         dependencies to the latex generated by matlab publish:
%
%  \usepackage[margin=1in]{geometry}
%  \usepackage{amsmath}
%  \usepackage{amssymb}
%  \usepackage{microtype}
%  \usepackage{csquotes}
%  \usepackage{bm}
%
% It is also recommended to use the following command to stop matrices
% from wrapping.
%
%  \setcounter{MaxMatrixCols}{20}
%

%% An Elliptic PDE Instance
%
% Consider a 2D metal block denoted by the region
% $\Omega = [0,4] \times [0, 2]$.
% The following PDE defines the temperature distribution throughout the
% block given von Neumann Boundary Conditions on the upper and lower
% boundaries, and Dirichlet Boundary Conditions on the left and right
% boundaries.
%
% $$ \begin{aligned}
%  \nabla^2 T = 0, && \forall~(x,y) \in \Omega \\
%  T(0, y) = 300, && T(4, y) = 600, && \forall~y \in [0, 2] \\
%  \frac{\partial T}{\partial y}(x, 0) = 0,
%    && \frac{\partial T}{\partial y}(x, 2) = 0,
%    && \forall~x \in [0, 4] \\
% \end{aligned} $$
%

%% C.5.1.1 - Numerically Solve the PDE
%
% First, we discretize space using a uniform stepsize $h$ as suggested in
% the text, with ghost points along $y = -h$ and $y = 2+h$.
% This results in a grid of points $x_{ij}$ where
% $x_{ij} = (x_j, y_i) = (hj, h(i-1)),
%  \forall~ i = 0, 1, \ldots, M+1 = 2/h + 2~\text{and}~
%  j = 0, 1, \ldots, N+1 = 4/h$.
% We then define our approximate solution
% $T_{ij} = T(x_{ij}) = T(x_j, y_i)$.
% 
% Now we define our FD approximations for the derivatives in our PDE
% system:
%
% $$ \begin{aligned}
%  \nabla^2T(x_j, y_i) &\approx 
%    \frac{T_{i+1,j} - 2T_{ij} + T_{i-1,j}}{h} +
%    \frac{T_{i,j+1} - 2T_{ij} + T_{i,j-1}}{h} \\
%    &= \frac{1}{h}
%    \left( T_{i+1,j} + T_{i-1,j} + T_{i,j+1} + T_{i,j-1} - 4T_{ij}\right)
%    = 0 && \forall~i = 1, 2, \ldots, M~\text{and}~j= 1, 2, \ldots, N  \\
%  \frac{\partial T}{\partial y}(x_j, 0)
%    &\approx \frac{T_{2j} - T_{0j}}{2h} = 0 
%     && \forall~j = 1, 2, \ldots, N \\
%  \frac{\partial T}{\partial y}(x_j, 2)
%    &\approx \frac{T_{M+1,j} - T_{M-1,j}}{2h} = 0
%     && \forall~j = 1, 2, \ldots, N \\
%  T(0, y_i) &\approx T_{i0} = 300, \quad T(4, y_i) \approx T_{i,N+1} = 600
%    && \forall~i = 1, 2, \ldots, M
% \end{aligned} $$
%
% Notice that none of the above constraints operate on the values
% $T_{00}, T_{0,N+1}, T_{M+1,0}, T_{M+1,N+1}$. Since none of these values
% are in $\overline{\Omega}$, we just set them explicitly to 0.
%
% Let the vector
% $\bm{T} = \begin{pmatrix} T_{00}, T_{10}, \ldots,
%                           T_{M+1,0}, T_{01}, T_{11}, \ldots, 
%                           T_{M,N+1}, T_{M+1,N+1} \end{pmatrix}^\top$
% be a flattened representation of our approximate solution $T_{ij}$.
% Then we can represent the PDE constraints of our system as
%
% $$ \begin{aligned}
%  A_1 \bm{T} &= \bm0_{NM}, \\
%  A_1 &= \begin{pmatrix}
%   0 &  1 & 0 & \bm{0}_{M-1} &
%   1 & -4 & 1 & \bm{0}_{M-1} &
%   0 &  1 & 0 & \multicolumn{5}{c}{\cdots} & 0 \\ 
%   0 & 0 &  1 & 0 & \bm{0}_{M-1} &
%       1 & -4 & 1 & \bm{0}_{M-1} &
%       0 &  1 & 0 & \multicolumn{4}{c}{\cdots} & 0 \\ 
%   0 & 0 &      0 & \ddots & \ddots & \ddots
%         & \ddots & \ddots & \ddots & \ddots
%         & \ddots & \ddots & 0 & \multicolumn{3}{c}{\cdots} & 0 \\
%   \multicolumn{17}{c}{\vdots} \\
%   \bm{0}_{M-1} & 0 &  1 & 0 & \bm{0}_{M-1} &
%                  1 & -4 & 1 & \bm{0}_{M-1} &
%                  0 &  1 & 0 & \multicolumn{4}{c}{\cdots} & 0 \\
%   \bm{0}_{M-1} & 0 & 0 & 0 & 0 &  1 & 0 & \bm{0}_{M-1} &
%                              1 & -4 & 1 & \bm{0}_{M-1} &
%                              0 &  1 & 0 & \cdots & 0 \\
%   \multicolumn{17}{c}{\vdots} \\
%   0 & \multicolumn{4}{c}{\cdots} & 0 &  1 & 0 & \bm{0}_{M-1} &
%                                    1 & -4 & 0 & \bm{0}_{M-1} & 
%                                    0 &  1 & 0 & 0 \\
%   0 & \multicolumn{4}{c}{\cdots} & 0 & 0 &  1 & 0 & \bm{0}_{M-1} &
%                                    1 & -4 & 0 & \bm{0}_{M-1} & 
%                                    0 &  1 & 0 \\
%  \end{pmatrix}.
% \end{aligned} $$
%
% Notice that $A_1 \in \mathbb{R}^{NM \times (N+2)(M+2)}$ and is made up
% of $N$ banded blocks of $M$ equations each. Each block shares the same
% band $\begin{pmatrix} 0 &  1 & 0 & \bm{0}_{M-1} &
%                       1 & -4 & 0 & \bm{0}_{M-1} &
%                       0 &  1 & 0 \end{pmatrix}$,
% and between each block there is an offset of 3 entries
% (as illustrated in the middle section of $A_1$ which shows the
%  border of block 1 and block 2).
% Another way to view this matrix is as a banded matrix with the above band
% justified at the top left corner where any row
% $k$ s.t. $k \equiv M+1 (\mod M+2)$ or $k \equiv M+2 (\mod M+2)$
% is omitted.
% 
% The von Neumann BCs can similarly be represented by a matrix system:
% 
% $$ \begin{aligned}
%  A_2 \bm{T} &= \bm{0}_{2N} \\
%  A_2 &= \begin{pmatrix}
%   \bm{0}_{M+2}            & -1 & 0 & 1 & 0 & \cdots & 0 \\
%   \bm{0}_{2(M+2) - 3}     & -1 & 0 & 1 & 0 & \cdots & 0 \\
%   \bm{0}_{2(M+2)}         & -1 & 0 & 1 & 0 & \cdots & 0 \\
%   \multicolumn{7}{c}{\vdots} \\
%   \bm{0}_{N(M+2)}         & -1 & 0 & 1 & 0 & \cdots & 0 \\
%   \bm{0}_{(N+1)(M+2) - 3} & -1 & 0 & 1 & \multicolumn{3}{c}{\bm{0}_{M+2}}
%  \end{pmatrix}.
% \end{aligned} $$
%
% Note that $A_2 \in \mathbb{R}^{2N \times (N+2)(M+2)}$ and is essentially
% a matrix with band $\begin{pmatrix} -1 & 0 & 1 \end{pmatrix}$ 
% justified at the top left corner where only rows
% $k$ s.t. $k \equiv 1 (\mod M+2)$ or $k \equiv M (\mod M+2)$
% are included.
% Furthermore, rows $k = 1, M, (N+1)(M+2) + 1, (N+2)(M+2) - 2$ are omitted
% depite satisfying the modulus equations above
% (they would correspond to the BCs at x_0 and x_{N+1}).
% 
% Finally, we can write our Dirichlet BCs and the constraints on the
% corners of our discrete grid as a simple matrix system:
%
% $$ \begin{aligned}
%  A_3 \bm{T} &= \bm{b} \\
%  A_3 &= \begin{pmatrix}
%   0 & 1 & 0 & 0 & 0 & \cdots & 0 \\
%   0 & 0 & 1 & 0 & 0 & \cdots & 0 \\
%   0 & 0 & 0 & \ddots & 0 & \cdots & 0 \\
%   \multicolumn{7}{c}{\vdots} \\
%   \bm{0}_M & 1 & 0 & 0 & 0 & \cdots & 0 \\
%   0 & \cdots & 0 & 0 & 1 & \multicolumn{2}{r}{\bm{0}_M} \\
%   0 & \cdots & 0 & 0 & 0 & \ddots & \vdots \\
%   \multicolumn{7}{c}{\vdots} \\
%   0 & \cdots & 0 & 0 & 0 & 1 & 0 \\
%   1 & 0 & 0 & 0 & 0 & \cdots & 0 \\
%   \bm0_{M+1} & 1 & 0 & 0 & 0 & \cdots & 0 \\
%   0 & \cdots & 0 & 0 & 0 & 1 & \bm0_{M+1} \\
%   0 & \cdots & 0 & 0 & 0 & 0 & 1 \\
%  \end{pmatrix},
%  \bm{b} = \begin{pmatrix}
%    300 \cdot \bm{1}_{N}^\top \\ 600 \cdot \bm{1}_{N}^\top \\
%    0 \\ 0 \\ 0 \\ 0
%  \end{pmatrix}
% \end{aligned} $$