%% Zachary Kaplan
 % Math 440 
 % Computational Lab #3 
 % 4/11/19
 
%
% An online version of this file can be found published to:
% https://www.overleaf.com/read/zgmxqsryykhj
% 
% *NOTE*: To render this file locally, please prepend the following package
%         dependencies to the latex generated by matlab publish:
%
%  \usepackage[margin=1in]{geometry}
%  \usepackage{amsmath}
%  \usepackage{amssymb}
%  \usepackage{microtype}
%  \usepackage{csquotes}
%  \usepackage{bm}
%

%% Parabolic PDE Instance
% 
% In this lab, we will consider the PDE describing the diffusion of heat
% through a metallic rod. 
%
% Let $L$ [ $m$ ] denote the length of the rod,
% $T$ [ $C$ ] denote the temperature of the rod across space and time,
% $\rho$ [ $kg/m^3$ ] denote the density of the rod,
% $C_p$ [ $J/(kg \cdot C)$ ] denote the heat capacity of the rod,
% and $k$ [ $J/(m \cdot s \cdot C)$ ] denote the thermal conductivity of
% the rod.
% We will consider this physical system over the 1-D spatial domain
% $x \,[m] \in \Omega = (0, L)$,
% and the temporal domain $t\,[s] \in (0, \infty)$.
% The following PDE then describes the difussion of heat through the rod:
%
% $$ 
%   \rho C_p \frac{\partial T}{\partial t} = 
%       k \frac{\partial^2 T}{\partial x^2},
%       \quad \forall (x, t) \in \Omega \times (0, \infty).
% $$
%
% We want to consider this rod where a temperature step-pulse of amplitude
% $T_0$ occurs at the left endpoint $x = 0$ for time $t \in (0, t_p)$.
% On the right endpoint, we consider the rod to be isolated and so heat
% does not flow through where $x = L$.
% As such, our boundary and initial conditions are:
%
% $$ \begin{gathered}
%   T(0, t) =
%     \begin{cases} T_0 & 0 \le t \le t_p \\ 0 & t > t_p \end{cases}, \quad
%   \frac{\partial T}{\partial x}(L, t) = 0, \\
%   T(x, 0) = \begin{cases} T_0 & x = 0 \\ 0 & 0 < x \le L \end{cases}.
% \end{gathered} $$
%

%% C.4.1.1 - Dimensionless PDE
%
% In this section, we show that with the proper rescaling of our domain and
% function $T$, we can represent the above constraints on $T$ with
% dimensionless equations.
% Consider dimensionless parameters $\xi$ for space and $\tau$ for time,
% and the dimensionless function $u$ where
%
% $$ \begin{aligned}x = L\xi, && t = t_p\tau, && T = T_0u\end{aligned}. $$
%
% If we look at the endpoints of our original domain we see that
% $\xi|_{x = 0} = 0, \xi|_{x = L} = 1,
%   \tau|_{t = 0} = 0, \tau|_{t \to \infty} \to \infty$.
% As such, our dimensionless spatial domain becomes
% $\xi \in \hat\Omega = (0, 1)$, and our dimensionless temporal domain
% becomes $\tau \in (0, \infty)$.
% We can then write the partials of $T$ in terms of $u$, $\xi$, and $\tau$
% as
%
% $$ \begin{aligned}
%   \frac{\partial T}{\partial t} &=
%     \frac{\partial T_0u}{\partial \tau}\frac{\partial \tau}{\partial t} =
%     \frac{T_0}{t_p} \frac{\partial u}{\partial \tau}, \\
%   \frac{\partial T}{\partial x} &=
%     \frac{\partial T_0u}{\partial \xi^2} \frac{\partial \xi}{\partial x} =
%   \frac{T_0}{L} \frac{\partial u}{\partial \xi}, \\
%   \frac{\partial^2 T}{\partial x^2} &=
%     \frac{\partial^2 T_0u}{\partial \xi^2}
%        \left(\frac{\partial \xi}{\partial x}\right)^2 =
%   \frac{T_0}{L^2} \frac{\partial^2 u}{\partial \xi^2}.
% \end{aligned} $$
%
% Substituting these values into the original PDE, we find
%
% $$ \begin{gathered}
%   \rho C_p \frac{T_0}{t_p} \frac{\partial u}{\partial \tau} =
%     k \frac{T_0}{L^2} \frac{\partial^2 u}{\partial \xi^2} \\
%   \implies \frac{\partial u}{\partial \tau} =
%     a \frac{\partial^2 u}{\partial \xi^2},
%   \quad (\xi, \tau) \in \hat\Omega \times (0, \infty),
% \end{gathered} $$
%
% where 
%
% $$ \begin{gathered}
%  a = \frac{k t_p}{\rho C_p L^2} ~\text{has units}~
%  \left[ \frac{J/(m \cdot s \cdot C) \cdot s}
%         {kg/m^3 \cdot J/(kg \cdot C) \cdot m^2} \right] \equiv
%  \left[ \frac{J}{J} \frac{1/m}{1/m^3 \cdot m^2} (1/s \cdot s) 
%    \frac{1/C}{1/C} \frac{1}{kg \cdot 1/kg} \right] \equiv [1]. \\
%  \therefore a~\text{is dimensionless}.
% \end{gathered} $$
%
% We can also substitute these equations into the boundary and initial
% conditions to obtain
%
% $$ \begin{aligned}
%   T(0 = x(0), t(\tau)) &= 
%   \begin{cases} 
%     T_0 & 0 \le t_p \tau \le t_p \\ 0 & t_p \tau > t_p 
%   \end{cases} = T_0 u(0, \tau)
%   &&\implies u(0, \tau) =
%   \begin{cases}
%     1 & 0 \le \tau \le 1 \\ 0 & \tau > 1
%   \end{cases}, \\
%   \frac{\partial T}{\partial x}(L = x(1), t(\tau)) &= 0 =
%     \frac{T_0}{L} \frac{\partial u}{\partial \xi}(1, \tau)
%   &&\implies \frac{\partial u}{\partial \xi}(1, \tau) = 0, \\
%   T(x(\xi), 0 = t(0)) &=
%     \begin{cases} T_0 & L\xi = 0 \\ 0 & 0 < L\xi \le L \end{cases} =
%   T_0 u(\xi, 0)
%   &&\implies u(\xi, 0) =
%     \begin{cases} 1 & \xi = 0 \\ 0 & 0 < \xi \le 1
%   \end{cases}.
% \end{aligned} $$
%
% From this point forward, this lab will only consider this dimensionless
% problem, fixing the dimensionless parameter $a = 1$.
%

